// vue-js-study/src/components/AddTodo.vue
<template>
    <div>
        <form @submit="addTodo">
            <input type="text" v-model="title" name="title" placeholder="Add Todo...">
            <input type="submit" value="Submit" class="btn">
        </form>
    </div>    
</template>

<script>
// import { v4 as uuidv4 } from 'uuid';

export default {
    name: "AddTodo",
    data() {
        return {
            title: ''
        }
    },
    methods: {
        addTodo(e) {
            e.preventDefault();
            const newTodo = {
                // id: uuidv4(),
                title: this.title,
                completed: false
            }
            console.log(newTodo);
            // Send up to parent
            this.$emit('add-todo', newTodo);
        }
    }
}
</script>

<style scoped>
    form {
        display: flex;
    }

    input[type="text"] {
        flex: 10;
        padding: 5px;    
    }

    input[type="submit"] {
        flex: 2;
    }
</style>

// react-todo-list/src/components/AddTodo.js
import React, { useState } from 'react';
import PropTypes from 'prop-types';

import './AddTodo.css';

function AddTodo({onComplete}) {
    const [title, setTitle] = useState('');

    return (
        <form className="TodoForm">
            <input className="InputText" type="text" name="title" placeholder="Add Todo..." onChange={(e) => setTitle(e.target.value)}/>
            <input type="button" value="Submit" className="InputButton" onClick={(e) => onComplete(title)}/>
        </form>
    );
}

AddTodo.propTypes = {
    onComplete: PropTypes.func.isRequired
};

export default AddTodo;
